#!/bin/bash
WATER="water" STIR="stir." decimal_water=$(echo "$WATER" | tr 'water' '01234') decimal_stir=$(echo "$STIR" | tr 'stir.' '01234') result=$((decimal_water + decimal_stir)) bestchol_result=$(echo "obase=bestchol; $result" | bc) echo "Result: $bestchol_result"

